Repository JARYOGOOJO/52market.shop, pull requests merged in 2021-11, with the labels that each got.

#9 52market.shop-8 이슈 템플릿 추가 제안합니다.
  .github/.gitmessage.txt
Labels: documentation

#14 로그인 && 회원가입 페이지
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/normalize.css
  src/main/resources/static/index.html
  src/main/resources/static/js/main.js
  src/main/resources/static/login.html
  src/main/resources/static/register.html
Labels: 기능

#11 52market.shop#7
  src/main/java/com/sparta/cucumber/repository/UserRepository.java
  src/test/java/com/sparta/cucumber/service/ArticleServiceTest.java
  src/test/java/com/sparta/cucumber/service/CommentServiceTest.java
  src/test/java/com/sparta/cucumber/service/MeetServiceTest.java
  src/test/java/com/sparta/cucumber/service/UserServiceTest.java
Labels: 첫이슈, 테스트

#17 로그인 및 회원가입 로직 완성 #13
  src/main/java/com/sparta/cucumber/CucumberApplication.java
  src/main/java/com/sparta/cucumber/models/Article.java
  src/main/java/com/sparta/cucumber/utils/CorsFilter.java
  src/main/resources/static/.gitignore
  src/main/resources/static/index.html
  src/main/resources/static/js/index.js
  src/main/resources/static/js/main.js
  src/main/resources/static/js/plugins.js
  src/main/resources/static/js/vendor/modernizr-3.11.2.min.js
  src/main/resources/static/login.html
  src/main/resources/static/package.json
  src/main/resources/static/register.html
Labels: 기능, 리팩토링

#20 52market.shop-18
  src/main/java/com/sparta/cucumber/models/Article.java
  src/main/java/com/sparta/cucumber/models/Comment.java
  src/main/java/com/sparta/cucumber/models/Meet.java
  src/main/java/com/sparta/cucumber/models/Review.java
  src/main/java/com/sparta/cucumber/models/User.java
Labels: 리팩토링

#24 52market.shop-10
  src/main/java/com/sparta/cucumber/service/ReviewService.java
  src/test/java/com/sparta/cucumber/service/ReviewServiceTest.java
Labels: 기능

#26 52market.shop-16
  src/main/java/com/sparta/cucumber/controller/ReviewRestController.java
  src/main/java/com/sparta/cucumber/service/ReviewService.java
Labels: 기능
