Repository JARYOGOOJO/52market.shop, pull requests merged in 2021-12, with the labels that each got.

#32 52market.shop-28
  build.gradle
  src/main/java/com/sparta/cucumber/config/WebSocketConfig.java
  src/main/java/com/sparta/cucumber/controller/ChatController.java
  src/main/java/com/sparta/cucumber/dto/ChatRequestDto.java
  src/main/java/com/sparta/cucumber/models/Article.java
  src/main/java/com/sparta/cucumber/models/ChatRoom.java
  src/main/java/com/sparta/cucumber/models/EnterRoom.java
  src/main/java/com/sparta/cucumber/repository/ChatRoomRepository.java
  src/main/java/com/sparta/cucumber/service/ChatService.java
Labels: 기능

#33 52market.shop-27
  build.gradle
  src/main/java/com/sparta/cucumber/controller/ArticleRestController.java
  src/main/java/com/sparta/cucumber/dto/ArticleRequestDto.java
  src/main/java/com/sparta/cucumber/models/Article.java
  src/main/java/com/sparta/cucumber/service/ArticleService.java
  src/main/resources/application-dev.properties
Labels: 기능, 도움

#34 소셜 로그인 버튼 활성화 및 토큰 발행까지 구현
  src/main/java/com/sparta/cucumber/service/CommentService.java
  src/main/resources/static/callback.html
  src/main/resources/static/css/main.css
  src/main/resources/static/empty.html
  src/main/resources/static/images/icon-52.png
  src/main/resources/static/images/icon-fb.png
  src/main/resources/static/images/icon-gg.png
  src/main/resources/static/images/icon-kk.png
  src/main/resources/static/images/icon-na.png
  src/main/resources/static/index.html
  src/main/resources/static/js/index.js
  src/main/resources/static/js/kakao.js
  src/main/resources/static/js/naveridlogin_js_sdk_2.0.2.js
  src/main/resources/static/login.html
  src/main/resources/static/register.html
Labels: 기능

#44 52market.shop#3
  build.gradle
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/dto/ArticleRequestDto.java
  src/main/java/com/sparta/cucumber/dto/JwtResponseDto.java
  src/main/java/com/sparta/cucumber/dto/SocialLoginDto.java
  src/main/java/com/sparta/cucumber/models/Role.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/repository/UserRepository.java
  src/main/java/com/sparta/cucumber/security/JwtAuthenticationEntryPoint.java
  src/main/java/com/sparta/cucumber/security/JwtAuthenticationFilter.java
  src/main/java/com/sparta/cucumber/security/UserDetailsImpl.java
  src/main/java/com/sparta/cucumber/security/kakao/KakaoOAuth2.java
  src/main/java/com/sparta/cucumber/security/kakao/KakaoUserInfo.java
  src/main/java/com/sparta/cucumber/security/kakao/UserDetailsServiceImpl.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/java/com/sparta/cucumber/utils/JwtTokenUtil.java
  src/main/java/com/sparta/cucumber/utils/WebSecurityConfig.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/main/resources/static/callback.html
  src/main/resources/static/js/index.js
  src/main/resources/static/login.html
Labels: 기능

#41 52market.shop-39
  src/main/java/com/sparta/cucumber/controller/ChatController.java
  src/main/java/com/sparta/cucumber/dto/ChatRequestDto.java
  src/main/java/com/sparta/cucumber/repository/EnterRoomRepository.java
  src/main/java/com/sparta/cucumber/service/ChatService.java
Labels: 기능

#36 52market.shop-35
  src/main/java/com/sparta/cucumber/controller/ChatController.java
  src/main/java/com/sparta/cucumber/models/EnterRoom.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/test/java/com/sparta/cucumber/service/ChatServiceTest.java
Labels: 테스트

#47 52market.shop-46
  .gitignore
  src/main/java/com/sparta/cucumber/models/EnterRoom.java
  src/main/java/com/sparta/cucumber/repository/EnterRoomRepository.java
  src/main/java/com/sparta/cucumber/service/ChatService.java
  src/main/resources/application.properties
  src/test/java/com/sparta/cucumber/models/ArticleTest.java
Labels: 기능

#50 52market.shop-48
  src/main/java/com/sparta/cucumber/controller/ChatController.java
  src/main/java/com/sparta/cucumber/service/ChatService.java
Labels: 기능

#51 파일 업로드 프론트단까지 완성
  src/main/java/com/sparta/cucumber/controller/ArticleRestController.java
  src/main/java/com/sparta/cucumber/dto/UserRequestDto.java
  src/main/java/com/sparta/cucumber/models/EnterRoom.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/repository/UserRepository.java
  src/main/java/com/sparta/cucumber/security/UserDetailsImpl.java
  src/main/java/com/sparta/cucumber/security/kakao/KakaoOAuth2.java
  src/main/java/com/sparta/cucumber/service/ChatService.java
  src/main/java/com/sparta/cucumber/service/ReviewService.java
  src/main/java/com/sparta/cucumber/service/S3Uploader.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/resources/static/css/main.css
  src/main/resources/static/index.html
  src/main/resources/static/js/index.js
  src/main/resources/static/login.html
  src/test/java/com/sparta/cucumber/service/UserServiceTest.java
Labels: 기능, 리팩토링

#52 게시글 수정 및 댓글 작성 기능 구현
  src/main/java/com/sparta/cucumber/controller/ArticleRestController.java
  src/main/java/com/sparta/cucumber/controller/CommentRestController.java
  src/main/java/com/sparta/cucumber/dto/ArticleRequestDto.java
  src/main/java/com/sparta/cucumber/models/Article.java
  src/main/java/com/sparta/cucumber/service/ArticleService.java
  src/main/resources/static/css/bootstrap.min.css
  src/main/resources/static/css/main.css
  src/main/resources/static/index.html
  src/main/resources/static/js/index.js
  src/main/resources/static/js/naveridlogin_js_sdk_2.0.2.js
  src/main/resources/static/login.html
  src/main/resources/static/package.json
Labels: 기능

#58 52market.shop-57
  src/main/java/com/sparta/cucumber/controller/ChatController.java
Labels: 기능

#59 #49 게시글 사진 삭제 메소드
  src/main/java/com/sparta/cucumber/controller/ArticleRestController.java
  src/main/java/com/sparta/cucumber/service/S3Uploader.java
Labels: 기능

#62 #53 댓글 기능 다시 수정
  src/main/java/com/sparta/cucumber/config/AmazonS3Config.java
  src/main/java/com/sparta/cucumber/config/WebConfig.java
  src/main/java/com/sparta/cucumber/config/WebSecurityConfig.java
  src/main/java/com/sparta/cucumber/controller/ChatController.java
  src/main/java/com/sparta/cucumber/controller/CommentRestController.java
  src/main/java/com/sparta/cucumber/models/Article.java
  src/main/java/com/sparta/cucumber/models/Comment.java
  src/main/java/com/sparta/cucumber/repository/CommentRepository.java
  src/main/java/com/sparta/cucumber/service/CommentService.java
  src/main/java/com/sparta/cucumber/service/MeetService.java
  src/main/java/com/sparta/cucumber/service/ReviewService.java
  src/main/resources/static/src/index.js
Labels: 기능

#61 #55 사진 업로드 메소드 수정
  src/main/java/com/sparta/cucumber/controller/ArticleRestController.java
  src/main/java/com/sparta/cucumber/service/ArticleService.java
Labels: 리팩토링

#60 #38 사용자 프로필 수정 시 사진 업로드 기능추가
  .gitignore
  package-lock.json
  package.json
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/dto/UserRequestDto.java
  src/main/java/com/sparta/cucumber/models/EnterRoom.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/repository/EnterRoomRepository.java
  src/main/java/com/sparta/cucumber/service/ChatService.java
  src/main/java/com/sparta/cucumber/service/S3Uploader.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/dist/125e84d3c8f273bf0b7a.png
  src/main/resources/static/dist/bundle.js
  src/main/resources/static/dist/bundle.js.LICENSE.txt
  src/main/resources/static/dist/d732f0f9cc860c3cea79.png
  src/main/resources/static/dist/index.html
  src/main/resources/static/package.json
  src/main/resources/static/src/css/main.css
  src/main/resources/static/src/index.html
  src/main/resources/static/src/index.js
Labels: 기능

#66 52market.shop-65
  .gitignore
  build.gradle
  src/main/java/com/sparta/cucumber/config/SwaggerConfig.java
  src/main/java/com/sparta/cucumber/config/WebSecurityConfig.java
  src/main/java/com/sparta/cucumber/controller/ArticleRestController.java
  src/main/java/com/sparta/cucumber/controller/ChatController.java
  src/main/java/com/sparta/cucumber/controller/CommentRestController.java
  src/main/java/com/sparta/cucumber/controller/HealthCheckController.java
  src/main/java/com/sparta/cucumber/controller/MeetRestController.java
  src/main/java/com/sparta/cucumber/controller/ReviewRestController.java
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
Labels: 문서, 기능

#67 프론트 메세지 템플릿 구현
  src/main/java/com/sparta/cucumber/config/WebSocketConfig.java
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/service/S3Uploader.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/resources/static/dist/125e84d3c8f273bf0b7a.png
  src/main/resources/static/dist/bundle.js
  src/main/resources/static/dist/bundle.js.LICENSE.txt
  src/main/resources/static/dist/d732f0f9cc860c3cea79.png
  src/main/resources/static/dist/index.html
  src/main/resources/static/package.json
  src/main/resources/static/src/css/main.css
  src/main/resources/static/src/index.js
Labels: 기능

#80 로그인 안되는 부분 수정..
  settings.gradle
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/dist/bundle.js
  src/main/resources/static/src/index.js
Labels: 버그, 기능, 미작동

#95 52market.shop#77 로그인문제 미적용 수정
  src/main/java/com/sparta/cucumber/chat/Meet.java
  src/main/java/com/sparta/cucumber/chat/MeetRepository.java
  src/main/java/com/sparta/cucumber/chat/MeetRequestDto.java
  src/main/java/com/sparta/cucumber/chat/MeetRestController.java
  src/main/java/com/sparta/cucumber/chat/MeetService.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/resources/static/package.json
  src/main/resources/static/src/index.js
  src/main/resources/static/src/view.js
  src/main/resources/static/webpack.config.js
Labels: 기능, 미작동, 리팩토링

#101 52market.shop#100
  .gitignore
  doc/swagger-ui-bundle.js
  src/main/java/com/sparta/cucumber/chat/ChatController.java
  src/main/java/com/sparta/cucumber/config/WebSecurityConfig.java
  src/main/java/com/sparta/cucumber/controller/ArticleRestController.java
  src/main/java/com/sparta/cucumber/controller/CommentRestController.java
  src/main/java/com/sparta/cucumber/controller/HealthCheckController.java
  src/main/java/com/sparta/cucumber/controller/ReviewRestController.java
  src/main/java/com/sparta/cucumber/service/ArticleService.java
  src/main/resources/application.properties
Labels: 미작동, 리팩토링

#103 52market.shop-102
  src/main/java/com/sparta/cucumber/chat/ChatRequestDto.java
  src/main/java/com/sparta/cucumber/chat/ChatRoom.java
  src/main/java/com/sparta/cucumber/chat/ChatService.java
  src/main/java/com/sparta/cucumber/chat/MessageController.java
  src/main/java/com/sparta/cucumber/models/User.java
Labels: 기능

#104 #91 리뷰기능 수정
  src/main/java/com/sparta/cucumber/controller/ReviewRestController.java
  src/main/java/com/sparta/cucumber/dto/ReviewRequestDto.java
  src/main/java/com/sparta/cucumber/models/Review.java
  src/main/java/com/sparta/cucumber/repository/ReviewRepository.java
  src/main/java/com/sparta/cucumber/service/ReviewService.java
Labels: 기능, 리팩토링

#108 52market.shop-107
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/dto/JwtResponseDto.java
Labels: 기능, 리팩토링

#113 52market.shop-112
  build.gradle
  src/main/java/com/sparta/cucumber/chat/RedisPublisher.java
  src/main/java/com/sparta/cucumber/chat/RedisService.java
  src/main/java/com/sparta/cucumber/chat/RedisSubscriber.java
  src/main/java/com/sparta/cucumber/config/RedisConfig.java
Labels: 기능

#114 HTMLUNIT htmlEscape
  src/main/java/com/sparta/cucumber/chat/MessageController.java
  src/main/java/com/sparta/cucumber/service/ArticleService.java
  src/main/java/com/sparta/cucumber/service/CommentService.java
  src/main/java/com/sparta/cucumber/service/ReviewService.java
  src/main/java/com/sparta/cucumber/service/UserService.java
Labels: 미작동, 리팩토링

#115 코드 리팩토링 및 개선
  src/main/java/com/sparta/cucumber/CucumberApplication.java
  src/main/java/com/sparta/cucumber/chat/ChatController.java
  src/main/java/com/sparta/cucumber/chat/ChatRoom.java
  src/main/java/com/sparta/cucumber/chat/ChatRoomRepository.java
  src/main/java/com/sparta/cucumber/chat/ChatService.java
  src/main/java/com/sparta/cucumber/chat/EnterRoom.java
  src/main/java/com/sparta/cucumber/chat/EnterRoomRepository.java
  src/main/java/com/sparta/cucumber/chat/MessageController.java
  src/main/java/com/sparta/cucumber/chat/RedisService.java
  src/main/java/com/sparta/cucumber/config/RedisConfig.java
  src/main/java/com/sparta/cucumber/controller/ArticleRestController.java
  src/main/java/com/sparta/cucumber/controller/HealthCheckController.java
  src/main/java/com/sparta/cucumber/controller/ReviewRestController.java
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/dto/CommentRequestDto.java
  src/main/java/com/sparta/cucumber/dto/ReviewRequestDto.java
  src/main/java/com/sparta/cucumber/models/Article.java
  src/main/java/com/sparta/cucumber/models/Comment.java
  src/main/java/com/sparta/cucumber/models/Review.java
  src/main/java/com/sparta/cucumber/models/Timestamped.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/redis/RedisPublisher.java
  src/main/java/com/sparta/cucumber/redis/RedisService.java
  src/main/java/com/sparta/cucumber/redis/RedisSubscriber.java
  src/main/java/com/sparta/cucumber/service/CommentService.java
  src/main/java/com/sparta/cucumber/service/S3Uploader.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/java/com/sparta/cucumber/utils/JwtTokenUtil.java
  src/main/java/com/sparta/cucumber/utils/LocationDistance.java
Labels: 리팩토링

#116 현재 유저 확인 후 토큰 재발급
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/dto/JwtRequestDto.java
  src/main/java/com/sparta/cucumber/dto/UserResponseDto.java
  src/main/java/com/sparta/cucumber/service/UserService.java
Labels: 기능

#118 52market.shop-117
  src/main/java/com/sparta/cucumber/chat/ChatController.java
  src/main/java/com/sparta/cucumber/chat/ChatRequestDto.java
  src/main/java/com/sparta/cucumber/chat/MessageController.java
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/redis/RedisSubscriber.java
  src/main/resources/application.properties
Labels: 기능

#121 error-handler
  src/main/java/com/sparta/cucumber/chat/ChatRoomService.java
  src/main/java/com/sparta/cucumber/chat/Notice.java
  src/main/java/com/sparta/cucumber/chat/NoticeService.java
  src/main/java/com/sparta/cucumber/error/CustomException.java
  src/main/java/com/sparta/cucumber/error/ErrorCode.java
  src/main/java/com/sparta/cucumber/error/ErrorResponse.java
  src/main/java/com/sparta/cucumber/error/GlobalExceptionHandler.java
  src/main/java/com/sparta/cucumber/models/Comment.java
  src/main/java/com/sparta/cucumber/models/Review.java
  src/main/java/com/sparta/cucumber/redis/RedisConfig.java
  src/main/java/com/sparta/cucumber/service/ArticleService.java
  src/main/java/com/sparta/cucumber/service/CommentService.java
  src/main/java/com/sparta/cucumber/service/ReviewService.java
  src/main/java/com/sparta/cucumber/service/UserService.java
Labels: 버그, 미작동, 리팩토링

#123 52market.shop-122
  src/main/java/com/sparta/cucumber/chat/ChatRoomController.java
  src/main/java/com/sparta/cucumber/chat/NoticeMessageController.java
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/redis/RedisPublisher.java
  src/main/java/com/sparta/cucumber/redis/RedisSubscriber.java
Labels: 기능, 리팩토링

#128 REDIS 채팅,유저알림 기능 구독 발행 추가 #124
  build.gradle
  src/main/java/com/sparta/cucumber/chat/ChatRequestDto.java
  src/main/java/com/sparta/cucumber/chat/ChatRoomController.java
  src/main/java/com/sparta/cucumber/chat/ChatRoomService.java
  src/main/java/com/sparta/cucumber/chat/Notice.java
  src/main/java/com/sparta/cucumber/chat/NoticeMessageController.java
  src/main/java/com/sparta/cucumber/models/Timestamped.java
  src/main/java/com/sparta/cucumber/redis/RedisPublisher.java
  src/main/java/com/sparta/cucumber/redis/RedisSubscriber.java
  src/main/resources/application.properties
Labels: 기능, 테스트, 리팩토링

#127 게시글과 댓글의 cascade 설정
  src/main/java/com/sparta/cucumber/models/Article.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/service/ArticleService.java
  src/main/java/com/sparta/cucumber/service/CommentService.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/java/com/sparta/cucumber/utils/JwtTokenUtil.java
Labels: 버그, 리팩토링

#129 #126 사라진 commentList 살려내기
  src/main/java/com/sparta/cucumber/models/Article.java
Labels: 버그, 미작동

#131 52market.shop-130
  src/main/java/com/sparta/cucumber/chat/ChatRoomController.java
  src/main/java/com/sparta/cucumber/chat/ChatRoomRepository.java
  src/main/java/com/sparta/cucumber/chat/ChatRoomService.java
  src/main/resources/application.properties
Labels: 기능

#132 가입 시 기존 유저 확인 및 가입/로케이션 분리
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/error/ErrorCode.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/java/com/sparta/cucumber/utils/ValidationUtil.java
Labels: 기능, 미작동, 리팩토링

#134 52market.shop-133
  src/main/java/com/sparta/cucumber/chat/ChatRoomController.java
  src/main/java/com/sparta/cucumber/chat/ChatRoomRepository.java
  src/main/java/com/sparta/cucumber/chat/ChatRoomService.java
Labels: 기능

#135 유저서비스 테스트케이스 #70
  .gitignore
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/dto/UserRequestDto.java
  src/main/java/com/sparta/cucumber/repository/UserRepository.java
  src/main/java/com/sparta/cucumber/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/test/java/com/sparta/cucumber/chat/ChatRoomTest.java
  src/test/java/com/sparta/cucumber/service/UserServiceTest.java
Labels: 문서, 테스트

#136 message
  src/main/java/com/sparta/cucumber/chat/ChatRequestDto.java
  src/main/java/com/sparta/cucumber/chat/NoticeService.java
  src/main/java/com/sparta/cucumber/error/ErrorCode.java
  src/test/java/com/sparta/cucumber/service/ChatRoomServiceTest.java
  src/test/java/com/sparta/cucumber/service/NoticeServiceTest.java
Labels: 테스트

#137 E2E 테스트 도입 (유저 컨트롤러 테스트)
  build.gradle
  src/main/java/com/sparta/cucumber/config/JwtTokenConfigure.java
  src/main/java/com/sparta/cucumber/config/WebSecurityConfig.java
  src/main/java/com/sparta/cucumber/controller/UserRestController.java
  src/main/java/com/sparta/cucumber/error/ErrorCode.java
  src/main/java/com/sparta/cucumber/models/User.java
  src/main/java/com/sparta/cucumber/security/UserDetailsServiceImpl.java
  src/main/java/com/sparta/cucumber/security/kakao/KakaoOAuth2.java
  src/main/java/com/sparta/cucumber/service/UserService.java
  src/main/java/com/sparta/cucumber/utils/JwtTokenUtil.java
  src/main/resources/application.properties
  src/test/java/com/sparta/cucumber/chat/ChatRoomTest.java
  src/test/java/com/sparta/cucumber/controller/UserRestControllerTest.java
  src/test/java/com/sparta/cucumber/service/NoticeServiceTest.java
  src/test/java/com/sparta/cucumber/service/UserServiceTest.java
Labels: 기능, 테스트, 리팩토링

#142 test: article controller 테스트코드
  src/test/java/com/sparta/cucumber/controller/ArticleRestControllerTest.java
Labels: 테스트
